global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "account-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["account-service:8081"]

  - job_name: "transaction-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["transaction-service:8082"]
